development:
  adapter: postgresql
  encoding: unicode
  database: cat_manager_test
  pool: 2
  username: your_username
  password: your_password

production:
  adapter: postgresql
  encoding: unicode
  database: cat_manager
  pool: 2
  username: your_username
  password: your_password
